// @flow

export const SHOW_USER_INFO = "SHOW_USER_INFO";
export const SHOW_USER_PHOTOS = "SHOW_USER_PHOTOS";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_USER_INFO_LOADING_STATUS = "SET_USER_INFO_LOADING_STATUS";

export const OPEN_CLOSE_MOBILE_MENU = "OPEN_CLOSE_MOBILE_MENU";

export const SET_VIEWPORT_VERSION = "SET_VIEWPORT_VERSION";

export const CHANGE_VAR = "CHANGE_VAR";

export const SET_VALUE = "SET_VALUE";
export const SET_NAME_VALUE = "SET_NAME_VALUE";
export const SET_SURNAME_VALUE = "SET_SURNAME_VALUE";
export const SET_APPOPTIONS_VALUE = "SET_APPOPTIONS_VALUE";
export const SET_PATRONYMIC_VALUE = "SET_PATRONYMIC_VALUE";
export const SET_TEL_VALUE = "SET_TEL_VALUE";
export const SET_EMAIL_VALUE = "SET_EMAIL_VALUE";
export const SET_EMOTIONS_VALUE = "SET_EMOTIONS_VALUE";
export const SET_ACHIEVE = "SET_ACHIEVE";
export const RESET_FORM = "RESET_FORM";

export const SET_SELFIE_ACHIEVE = "SET_SELFIE_ACHIEVE";
export const SET_BURNT_ACHIEVE = "SET_BURNT_ACHIEVE";
export const SET_SAWSELEB_ACHIEVE = "SET_SAWSELEB_ACHIEVE";
export const SET_SOUVENIRS_ACHIEVE = "SET_SOUVENIRS_ACHIEVE";
export const SET_HOLD_ACHIEVE = "SET_HOLD_ACHIEVE";
export const SET_DESTROY_ACHIEVE = "SET_DESTROY_ACHIEVE";

export const ADD_PHOTOS = "ADD_MORE_PHOTOS";
export const ADD_PANORAM = "ADD_PANORAM";

export const LIKE_PHOTO = "LIKE_PHOTO";
export const LIKE_PANORAM = "LIKE_PANORAM";
